name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: print the actor
        run: echo ${{ github.actor }}

      - name: Run a one-line script
        run: echo Hello, world!

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: my push
        run: |
          echo Hello from Github Actions
          echo ths is a new comment
          pwd
          ls
      - name: print linux info
        run: cat /etc/lsb-release
